jmilkfansblog/__init__.py
import os

from oslo_log import log as logging
from oslo_config import cfg

from flask import Flask
from flask.ext.login import current_user
from flask.ext.principal import identity_loaded, UserNeed, RoleNeed
from sqlalchemy import event

from jmilkfansblog.db.sqlalchemy.models import BrowseVolume, db, Post
from jmilkfansblog.db.sqlalchemy.models import Reminder, Role, Tag
from jmilkfansblog.controllers import blog
from jmilkfansblog.controllers import account
from jmilkfansblog.controllers.flask_restful.posts import PostApi
from jmilkfansblog.controllers.flask_restful.auth import AuthApi
from jmilkfansblog.extensions import bcrypt, openid, login_manager
from jmilkfansblog.extensions import principals, flask_celery
from jmilkfansblog.extensions import restful_api, debug_toolbar
from jmilkfansblog.extensions import cache, flask_admin
from jmilkfansblog.extensions import assets_env, main_js, main_css
from jmilkfansblog.extensions import youku
from jmilkfansblog.tasks import on_reminder_save
from jmilkfansblog.controllers import admin
from jmilkfansblog.i18n import _LI


LOG = logging.getLogger(__name__)
CONF = cfg.CONF


def create_app(object_name):
    """Create the app instance via `Factory Method`"""

    LOG.info(_LI("Creating the flask application object."))

    app = Flask(__name__)
    # Set the config for app instance
    app.config.from_object(object_name)

    # Init the Flask-SQLAlchemy via app boject
    # Will be load the SQLALCHEMY_DATABASE_URL from config.py to db object
    db.init_app(app)

    # Using the SQLAlchemy's event
    # Will be callback on_reminder_save when insert into table `reminder`.
    event.listen(Reminder, 'after_insert', on_reminder_save)

    # Init the Flask-Bcrypt via app object
    bcrypt.init_app(app)

    # Init the Flask-OpenID via app object
    openid.init_app(app)

    # Init the Flask-Login via app object
    login_manager.init_app(app)

    # Init the Flask-Prinicpal via app object
    principals.init_app(app)

    # Init the Flask-Celery-Helper via app object
    # Register the celery object into app object
    flask_celery.init_app(app)

    # Init the Flask-Restful via app object
    # Define the route of restful_api
    restful_api.add_resource(
        PostApi,
        '/api/posts',
        '/api/posts/<string:post_id>',
        endpoint='restful_api_post')

    restful_api.add_resource(
        AuthApi,
        '/api/auth',
        endpoint='restful_api_auth')
    restful_api.init_app(app)

    # Init the Flask-DebugToolbar via app object
    debug_toolbar.init_app(app)

    # Init the Flask-Cache via app object
    cache.init_app(app)

    # Init the Flask-Assets via app object
    assets_env.init_app(app)
    assets_env.register('main_js', main_js)
    assets_env.register('main_css', main_css)

    # Init the Flask-Admin via app object
    flask_admin.init_app(app)
    # Register view function `CustomView` into Flask-Admin
    flask_admin.add_view(admin.CustomView(name='Custom'))
    # Register view function `CustomModelView` into Flask-Admin
    models = [Role, Tag, Reminder, BrowseVolume]
    for model in models:
        flask_admin.add_view(
            admin.CustomModelView(model, db.session, category='Models'))
    # Register view function `PostView` into Flask-Admin
    flask_admin.add_view(
        admin.PostView(Post, db.session, name='PostManager'))
    # Register and define path of File System for Flask-Admin
    flask_admin.add_view(
        admin.CustomFileAdmin(
            os.path.join(os.path.dirname(__file__), 'static'),
            '/static',
            name='Static Files'))

    # Init the Flask-Youku via app object
    youku.init_app(app)

    # Init the Flask-GZip via app object
    # FIXME(Fan Guiju): UnicodeDecodeError
    #                   Have to setup the `DEBUG = False`
    # flask_gzip.init_app(app)

    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        """Change the role via add the Need object into Role.

           Need the access the app object.
        """

        # Set the identity user object
        identity.user = current_user

        # Add the UserNeed to the identity user object
        if hasattr(current_user, 'id'):
            identity.provides.add(UserNeed(current_user.id))

        # Add each role to the identity user object
        if hasattr(current_user, 'roles'):
            for role in current_user.roles:
                identity.provides.add(RoleNeed(role.name))

    # Register the Blueprint into app object
    app.register_blueprint(blog.blog_blueprint)
    app.register_blueprint(account.main_blueprint)

    return app

jmilkfansblog/controllers/admin.py
from flask.ext.admin import BaseView, expose
from flask.ext.admin.contrib.fileadmin import FileAdmin
from flask.ext.admin.contrib.sqla import ModelView
from flask.ext.login import login_required, current_user

from jmilkfansblog.extensions import admin_permission
from jmilkfansblog.forms import CKTextAreaField


class CustomView(BaseView):
    """View function of Flask-Admin for Custom page."""

    @expose('/')
    @login_required
    @admin_permission.require(http_exception=403)
    def index(self):
        return self.render('admin/custom.html')

    @expose('/second_page')
    @login_required
    @admin_permission.require(http_exception=403)
    def second_page(self):
        return self.render('admin/second_page.html')


class CustomModelView(ModelView):
    """View function of Flask-Admin for Models page."""

    def is_accessible(self):
        """Setup the access permission for CustomModelView."""

        # callable function `User.is_authenticated()`.
        # FIXME(JMilkFan): Using function is_authenticated()
        return current_user.is_authenticated() and\
            admin_permission.can()


class PostView(CustomModelView):
    """View function of Flask-Admin for Post create/edit Page includedin Models page"""

    # Using the CKTextAreaField to replace the Field name is `test`
    form_overrides = dict(text=CKTextAreaField)

    # Using Search box
    column_searchable_list = ('text', 'title')

    # Using Add Filter box
    column_filters = ('publish_date',)

    # Custom the template for PostView
    # Using js Editor of CKeditor
    create_template = 'admin/post_edit.html'
    edit_template = 'admin/post_edit.html'


class CustomFileAdmin(FileAdmin):
    """File System admin."""

    def is_accessible(self):
        """Setup the access permission for CustomFileAdmin."""

        # callable function `User.is_authenticated()`.
        return current_user.is_authenticated() and\
            admin_permission.can()

jmilkfansblog/controllers/admin/__init__.py
from flask.ext.admin import BaseView, expose
from flask.ext.admin.contrib.fileadmin import FileAdmin
from flask.ext.admin.contrib.sqla import ModelView
from flask.ext.login import login_required, current_user

from jmilkfansblog.extensions import admin_permission
from jmilkfansblog.forms import CKTextAreaField


class CustomView(BaseView):
    """View function of Flask-Admin for Custom page."""

    @expose('/')
    @login_required
    @admin_permission.require(http_exception=403)
    def index(self):
        return self.render('admin/custom.html')

    @expose('/second_page')
    @login_required
    @admin_permission.require(http_exception=403)
    def second_page(self):
        return self.render('admin/second_page.html')


class CustomModelView(ModelView):
    """View function of Flask-Admin for Models page."""

    def is_accessible(self):
        """Setup the access permission for CustomModelView."""

        # callable function `User.is_authenticated()`.
        # FIXME(JMilkFan):
        #     Using function is_authenticated(),
        #     Can return the value of current_user.is_authenticated()
        #     when user was logged in.
        return current_user.is_authenticated and\
            admin_permission.can()


class PostView(CustomModelView):
    """View function of Flask-Admin

       The View func for Post create/edit Page includedin Models page
    """

    # Using the CKTextAreaField to replace the Field name is `test`
    form_overrides = dict(text=CKTextAreaField)

    # Using Search box
    column_searchable_list = ('text', 'title')

    # Using Add Filter box
    column_filters = ('publish_date',)

    # Custom the template for PostView
    # Using js Editor of CKeditor
    create_template = 'admin/post_edit.html'
    edit_template = 'admin/post_edit.html'


class CustomFileAdmin(FileAdmin):
    """File System admin."""

    def is_accessible(self):
        """Setup the access permission for CustomFileAdmin."""

        # callable function `User.is_authenticated()`.
        return current_user.is_authenticated and\
            admin_permission.can()

jmilkfansblog/controllers/blog.py
from uuid import uuid4
from os import path
from datetime import datetime

from flask import render_template, redirect, Blueprint, url_for, flash
from flask import session, abort, request
from flask.ext.login import login_required, current_user
from flask.ext.principal import Permission, UserNeed
from sqlalchemy import func

from jmilkfansblog.models import db, User, Post, Tag, Comment, posts_tags
from jmilkfansblog.forms import CommentForm, PostForm
from jmilkfansblog.extensions import poster_permission, admin_permission, cache


blog_blueprint = Blueprint(
    'blog',
    __name__,
    # path.pardir ==> ../
    template_folder=path.join(path.pardir, 'templates', 'blog'),
    # Prefix of Route URL 
    url_prefix='/blog')


def make_cache_key(*args, **kwargs):
    """Dynamic creation the request url."""

    path = request.path
    args = str(hash(frozenset(request.args.items())))
    # lang = get_locale()
    # return (path + args + lang).encode('utf-8')
    return (path + args).encode('utf-8')


@cache.cached(timeout=7200, key_prefix='sidebar_data')
def sidebar_data():
    """Set the sidebar function."""

    # Get post of recent
    recent = db.session.query(Post).order_by(
            Post.publish_date.desc()
        ).limit(5).all()

    # Get the tags and sort by count of posts.
    top_tags = db.session.query(
            Tag, func.count(posts_tags.c.post_id).label('total')
        ).join(
            posts_tags
        ).group_by(Tag).order_by('total DESC').limit(5).all()
    return recent, top_tags


# Use the Blueprint object to set the Route URL
# Register the view function into blueprint
@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@cache.cached(timeout=60)
def home(page=1):
    """View function for home page"""

    posts = Post.query.order_by(
        Post.publish_date.desc()
    ).paginate(page, 10)

    recent, top_tags = sidebar_data()

    return render_template('home.html',
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/post/<string:post_id>', methods=('GET', 'POST'))
@cache.cached(timeout=60, key_prefix=make_cache_key)
def post(post_id):
    """View function for post page"""

    # Form object: `Comment`
    form = CommentForm()
    # form.validate_on_submit() will be true and return the
    # data object to form instance from user enter,
    # when the HTTP request is POST
    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.date = datetime.now()
        new_comment.post_id = post_id
        db.session.add(new_comment)
        db.session.commit()

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('post.html',
                           post=post,
                           tags=tags,
                           comments=comments,
                           form=form,
                           recent=recent,
                           top_tags=top_tags,
                           poster_permission=poster_permission,
                           admin_permission=admin_permission)


@blog_blueprint.route('/tag/<string:tag_name>')
def tag(tag_name):
    """View function for tag page"""

    tag = Tag.query.filter_by(name=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('tag.html',
                           tag=tag,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/user/<string:username>')
def user(username):
    """View function for user page"""
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('user.html',
                           user=user,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    """View function for new_port."""

    form = PostForm()

    # Ensure the user logged in.
    # Flask-Login.current_user can be access current user.
    if not current_user:
        return redirect(url_for('main.login'))

    # Will be execute when click the submit in the create a new post page.
    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.text = form.text.data
        new_post.publish_date = datetime.now()
        new_post.user = current_user

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('blog.home'))

    return render_template('new_post.html',
                           form=form)


@blog_blueprint.route('/edit/<string:id>', methods=['GET', 'POST'])
@login_required
@admin_permission.require(http_exception=403)
def edit_post(id):
    """View function for edit_post."""

    post = Post.query.get_or_404(id)

    # Ensure the user logged in.
    if not current_user:
        return redirect(url_for('main.login'))

    # Only the post onwer can be edit this post.
    if current_user != post.user:
        return redirect(url_for('blog.post', post_id=id))

    # Admin can be edit the post.
    permission = Permission(UserNeed(post.user.id))
    if permission.can() or admin_permission.can():
        form = PostForm()

        #if current_user != post.user:
        #    abort(403)

        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.publish_date = datetime.now()

            # Update the post
            db.session.add(post)
            db.session.commit()

            return redirect(url_for('blog.post', post_id=post.id))
    else:
        abort(403)

    # Still retain the original content, if validate is false.
    form.title.data = post.title
    form.text.data = post.text
    return render_template('edit_post.html', form=form, post=post)


# NOTE(Jmilk Fan): Use the Flask-Login's current_user object to replace
#                  g.current_user
# @blog_blueprint.before_request
def check_user():
    """Check the user whether logged in."""

    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session['username']).first()
    else:
        g.current_user = None


@blog_blueprint.errorhandler(404)
def page_not_found(error):
    """View function for user page not found"""
    return render_template('page_not_found.html'), 404

jmilkfansblog/controllers/flask_restful/auth.py
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

from flask import abort, current_app
from flask.ext.restful import Resource

from jmilkfansblog.controllers.flask_restful import parsers
from jmilkfansblog.db.sqlalchemy.models import User


class AuthApi(Resource):
    """Restful api of Auth."""

    def post(self):
        """Can be execute when receive HTTP Method `POST`."""

        args = parsers.user_post_parser.parse_args()
        user = User.query.filter_by(username=args['username']).first()

        # Check the args['password'] whether as same as user.password.
        if user.check_password(args['password']):
            # serializer object will be saved the token period of time.
            serializer = Serializer(
                current_app.config['SECRET_KEY'],
                expires_in=600)
            return {'token': serializer.dumps({'id': user.id})}
        else:
            abort(401)

jmilkfansblog/controllers/restful/auth.py
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

from flask import abort, current_app
from flask.ext.restful import Resource

from jmilkfansblog.controllers.restful import parsers
from jmilkfansblog.models import User


class AuthApi(Resource):
    """Restful api of Auth."""

    def post(self):
        """Can be execute when receive HTTP Method `POST`."""

        args = parsers.user_post_parser.parse_args()
        user = User.query.filter_by(username=args['username']).first()

        # Check the args['password'] whether as same as user.password.
        if user.check_password(args['password']):
            # serializer object will be saved the token period of time.
            serializer = Serializer(
                current_app.config['SECRET_KEY'],
                expires_in=600)
            return {'token': serializer.dumps({'id': user.id})}
        else:
            abort(401)

jmilkfansblog/templates/blog/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,, initial-scale=1">
  <!-- Will be replace the page title -->
  <title>{% block title %}Home{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <!-- Macro: `render paginate` -->
  {% macro render_pagination(pagination, endpoint) %}
    <nav>
      <ul class="pagination">
        <li>
        {% if pagination.has_prev %}
          <a href="{{ url_for('blog.home', page=pagination.prev().page)
            }}" aria-label="Previous">
        {% else %}
          <a href="{{ url_for('blog.home', page=1) }}" aria-label="Previous">
        {% endif %}
            <span aria-label="true">&laquo;</span>
          </a>
        </li>
        {% for page in pagination.iter_pages() %}
          {% if page %}
            {% if page != pagination.page %}
              <li>
                <a href="{{ url_for(endpoint, page=page) }}">
                  {{ page }}
                </a>
              </li>
            {% else %}
              <li><a href="">{{ page }}</a></li>
            {% endif %}
          {% else %}
            <li><a>...</a></li>
          {% endif %}
        {% endfor %}
        <li>
          <a href="{{ url_for('blog.home', page=pagination.next().page )
            }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        <li>
      </ul>
    </nav>
  {% endmacro %}
  {% block captcha %}
  {% endblock %}
</head>

<body>
  <div class="container">
    <div class="jumbotron">
      <!-- Replace the route function to URL: `/` -->
      <h1><a href="{{ url_for('blog.home')}} ">JmilkFan's Blog</a></h1>
        <p>Welcome to the blog!</p>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="button" class="close" data-dismiss="alert" aria-label="Close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ messages }}
          </div>
        {% endfor%}
      {% endif %}
    {% endwith %}
    {% block body %}
      body_content
    {% endblock %}
  </div>
  {# <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script> #}
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  {# <script
    src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> #}
  {# <script
    src="https://maxcdn.bootstrapcdn.com/bootsrtap/3.3.2/js/bootstrap.min.js"></script> #}
  {% block js %}
  {% endblock %}
</body>
</html>

jmilkfansblog/templates/blog/edit.html
{% extends "base.html" %}

{% block title %}Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Edit the Post</h1>
  <form method="POST" action="{{ url_for('blog.edit_post', id=post.id) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control', value=post.title) }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

jmilkfansblog/templates/blog/edit_post.html
{% extends "base.html" %}

{% block title %}Edit Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Edit The Post</h1>
  <form method="POST" action="{{ url_for('blog.edit_post', id=post.id) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control', value=post.title) }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
{% assets "main_js" %}
  <!-- <script src="{{ ASSET_URL }}"></script> -->
  <script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
  <!-- Use the CKEditor -->
  <script>
      CKEDITOR.replace('editor');
  </script>
{% endassets %}
{% endblock %}

jmilkfansblog/templates/blog/new.html
{% extends "base.html" %}

{% block title %}Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Create A New Post</h1>
  <form method="POST" action="{{ url_for('blog.new_post') }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control') }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

jmilkfansblog/templates/blog/new_post.html
{% extends "base.html" %}

{% block title %}New Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Create A New Post</h1>
  <form method="POST" action="{{ url_for('blog.new_post') }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control') }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
{% assets "main_js" %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<!-- <script src="{{ ASSET_URL }}"></script> -->
<script>
    CKEDITOR.replace('editor');
</script>
{% endassets %}
{% endblock %}

jmilkfansblog/templates/blog/page_not_found.html
{% extends 'base.html' %}
{% block title %}404 Not Found{% endblock %}

jmilkfansblog/templates/blog/post.html
<!-- Replace the TITLE of template base.html -->
{% extends "base.html"%}
{% block title %}{{ post.name }}{% endblock %}

<!-- Replace the BODY of template base.html -->
{% block body %}
<h3>{{ post.title }}</h3>

<div class="row">
  <div class="col-lg-6">
    <p>Written By <a href="{{ url_for('blog.user', username=post.user.username)
      }}">{{ post.user.username }}</a> on {{ post.publish_date }}</p>
    <p>{{ post.text | safe }}</p>
  </div>
  {% if current_user.is_authenticated %}
  <div class="column">
    <div class="col-lg-2">
      <a href="{{ url_for('blog.new_post') }}" class="btn btn-primary">New</a>
    </div>
  </div>
  {% endif %}
  {% if post.user == current_user or admin_permission.can() %}
  <div class="column">
    <div class="col-lg-2">
      <a href="{{ url_for('blog.edit_post', id=post.id) }}" class="btn btn-primary">Edit</a>
    </div>
  </div>
  {% endif %}
  <div class="col-lg-12">
    <h3>New Comment:</h3>
    <!-- Set the form -->
    {# <form method="POST" action="{{ url_for('blog.post', post_id=post.id)
      }}">
      {{ form.hidden_tag() }}
      <div class="row">
        <div class="col-lg-5">
          <!-- Field: `name` label -->
          {{ form.name.label }}
          {% if form.name.errors %}
            {% for e in form.name.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.name(class_="form-control") }}
        </div>
      </div>
      <div class="row">
        <div class="col-lg-10">
          {{ form.text.label }}
          {% if form.text.errors %}
            {% for e in form.text.errors %}
              <p class="help-block">{{ e }}</p>
            {% endfor %}
          {% endif %}
          {{ form.text(class_='form-control') }}
        </div>
      </div>
      <input class="btn btn-primary" type="submit" value="Add Comment">
    </form>
    <!-- Show the comments -->
    <div class="form-group">
      {% for comment in comments %}
        <h5>{{ comment.name }}:</h5>
        {{ comment.text }}
      {% endfor %}
    </div> #}
  <!-- duoshuo-share -->
  <div class="ds-share" data-thread-key="{{ post.id }}" data-title="{{ post.title }}" data-images="https://avatars0.githubusercontent.com/u/16975584?v=3&u=4994b2cb1d62530e95f1ef4a884fdaecb3245329&s=400" data-content="{{ post.text | truncate(100) }}" data-url="{{ url_for('blog.post', post_id=post.id )}}">
    <div class="ds-share-inline">
      <ul  class="ds-share-icons-16">
      	
      	<li data-toggle="ds-share-icons-more"><a class="ds-more" href="javascript:void(0);">分享到：</a></li>
        <li><a class="ds-weibo" href="javascript:void(0);" data-service="weibo">微博</a></li>
        <li><a class="ds-qzone" href="javascript:void(0);" data-service="qzone">QQ空间</a></li>
        <li><a class="ds-qqt" href="javascript:void(0);" data-service="qqt">腾讯微博</a></li>
        <li><a class="ds-wechat" href="javascript:void(0);" data-service="wechat">微信</a></li>
      	
      </ul>
      <div class="ds-share-icons-more"></div>
    </div>
  </div>
  <!-- duoshuo-comments -->
  <div class="ds-thread" data-thread-key="{{ post.id }}" data-title="{{ post.title }}" data-url="{{ url_for('blog.post', post_id=post.id) }}"></div>
  <script type="text/javascript">
    var duoshuoQuery = {short_name:"jmilkfan"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
  </script>
  </div>
</div>
{% endblock %}